<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.t_user" Member="t_user">
    <Type Name="t_user">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="pwd" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_categorie" Member="t_categorie">
    <Type Name="t_categorie">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="libelle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_article" Member="t_article">
    <Type Name="t_article">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="libelle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prix_unitaire" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="categorie" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_commande" Member="t_commande">
    <Type Name="t_commande">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Article_commandee" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantite" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Client_email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Date_commande" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="prix_totale" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Client" Member="t_Client">
    <Type Name="t_Client">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="client_nom" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="pawd" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </Type>
  </Table>
</Database>